# Exported from Render on 2024-09-05T08:44:54Z
services:
  - type: web
    name: ecommerce
    runtime: node
    repo: https://github.com/devfresher/ecommerce
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: .env
        sync: false
      - key: SEED_USER_AND_PRODUCTS
        sync: false
      - key: DB_URI
        sync: false
      - key: JWT_ACCESS_EXPIRES
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        sync: false
    region: oregon
    buildCommand: npm install; npm run build
    startCommand: npm run start
    healthCheckPath: /api/v1/
version: '1'
